name: Test

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sigs.k8s.io/cloud-provider-kind

permissions: write-all

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: stable
    - uses: actions/checkout@v5.0.0
    - run: make test
    - run: make lint

