name: Test

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sigs.k8s.io/cloud-provider-kind

permissions: write-all

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: stable
    - uses: actions/checkout@v5
    - run: make test
    - run: make lint

